### ISSUE TITLE
train.py的一个新错误

### ISSUE THREAD

**Issue by Qingmeiza** [Sharpiless/yolov5-distillation-5.0#10]
Traceback (most recent call last):
  File "C:/Users/qingmei/Desktop/yolov5-distillation-5.0-main/train.py", line 674, in <module>
    train(hyp, opt, device, tb_writer)
  File "C:/Users/qingmei/Desktop/yolov5-distillation-5.0-main/train.py", line 254, in train
    t_model) else t_model.model[-1]
UnboundLocalError: local variable 't_model' referenced before assignment

不知道该修改哪部分，有无大佬救一救（孩子跪求）

**Comment by WangYafei0904** [comment]
你解决了么

**Comment by sduaa** [comment]
我也碰到了

**Comment by 1781686573** [comment]
请问解决了吗大佬，我也碰到这个问题了

**Comment by sduaa** [comment]
解决了，在命令行 python train.py --distill 就好了，应该设定好这个模式，好像是这样吧
