### ISSUE TITLE
TypeError: 'builtin_function_or_method' object does not support item assignment

### ISSUE THREAD

**Issue by GitHub1002** [Sharpiless/yolov5-distillation-5.0#13]
Traceback (most recent call last):
  File "train.py", line 674, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 371, in train
    loss, loss_items = compute_loss(
  File "/home/dell2/FMK/yolov5-distillation-5.0/utils/loss.py", line 184, in __call__
    tcls, tbox, indices, anchors = self.build_targets(
  File "/home/dell2/FMK/yolov5-distillation-5.0/utils/loss.py", line 255, in build_targets
    gain[2:6] = torch.tensor(p[i].shape)[[3, 2, 3, 2]]  # xyxy gain
TypeError: 'builtin_function_or_method' object does not support item assignment

**Comment by xyh001007** [comment]
do you solve it?

**Comment by HeadInTheClouds97** [comment]
In loss.py  167lines
gain = torch.ones(7, device=targets.device).long 
to 
gain = torch.ones(7, device=targets.device).long()
